### ISSUE TITLE
请教大佬，最后这个问题您有找到解决思路吗

### ISSUE THREAD

**Issue by LOMOGO** [PalmsSA/AlphaPose_npu#1]
请教大佬，最后这个问题您有找到解决思路吗？是 atc 模型转换后的 om 文件的问题吗

**Comment by PalmsSA** [comment]
> 请教大佬，最后这个问题您有找到解决思路吗？是 atc 模型转换后的 om 文件的问题吗

最后的问题是指什么，我记得这个项目当时我遇到的问题是模型输出不对，我改完后完全能正确运行的

**Comment by LOMOGO** [comment]
> > 请教大佬，最后这个问题您有找到解决思路吗？是 atc 模型转换后的 om 文件的问题吗
> 
> 最后的问题是指什么，我记得这个项目当时我遇到的问题是模型输出不对，我改完后完全能正确运行的

首先预祝大佬新年快乐，不好意思麻烦大佬了，我描述的可能不清楚，“最后的问题”指的是模型输出的结果不对，我按照您的代码正常的跑出来了结果，但是预测的结果和您在 ascend 社区里面的帖子的结果一样，有一些点位对不上。请问您最后是怎么修复这个模型输出不对的结果的。

**Comment by LOMOGO** [comment]
我运行出来的输出结果是下图这样的：
![image](https://github.com/PalmsSA/AlphaPose_npu/assets/46417831/2283ad48-4b4d-40f7-966e-924bd57387d8)

**Comment by PalmsSA** [comment]
> > > 请教大佬，最后这个问题您有找到解决思路吗？是 atc 模型转换后的 om 文件的问题吗
> > 
> > 
> > 最后的问题是指什么，我记得这个项目当时我遇到的问题是模型输出不对，我改完后完全能正确运行的
> 
> 首先预祝大佬新年快乐，不好意思麻烦大佬了，我描述的可能不清楚，“最后的问题”指的是模型输出的结果不对，我按照您的代码正常的跑出来了结果，但是预测的结果和您在 ascend 社区里面的帖子的结果一样，有一些点位对不上。请问您最后是怎么修复这个模型输出不对的结果的。

时间太久了，我给忘记了具体怎么做了，问题是某个输出的特征维度反了。这里我有两种解决方案，第一种是在acl 那边的模型后处理做修改，第二种是直接修改onnx模型，但是我都忘记怎么操作了，要不我直接给你最后的om的模型？

**Comment by PalmsSA** [comment]
> > > > 请教大佬，最后这个问题您有找到解决思路吗？是 atc 模型转换后的 om 文件的问题吗
> > > 
> > > 
> > > 最后的问题是指什么，我记得这个项目当时我遇到的问题是模型输出不对，我改完后完全能正确运行的
> > 
> > 
> > 首先预祝大佬新年快乐，不好意思麻烦大佬了，我描述的可能不清楚，“最后的问题”指的是模型输出的结果不对，我按照您的代码正常的跑出来了结果，但是预测的结果和您在 ascend 社区里面的帖子的结果一样，有一些点位对不上。请问您最后是怎么修复这个模型输出不对的结果的。
> 
> 时间太久了，我给忘记了具体怎么做了，问题是某个输出的特征维度反了。这里我有两种解决方案，第一种是在acl 那边的模型后处理做修改，第二种是直接修改onnx模型，但是我都忘记怎么操作了，要不我直接给你最后的om的模型？

https://cowtransfer.com/s/a4c52f07670244

**Comment by LOMOGO** [comment]
> 某个输出的特征维度反了。这里我有两种解决方案，第一种是在acl 那边的模型后处理做修改，第二种是直接修改onnx模型，但是我都忘记怎么操作了，要不我直接给你最后的om的模型？

首先感谢大佬，抱歉，这个模型的下载链接失效了，可以麻烦您再补一个吗，谢谢啦

**Comment by PalmsSA** [comment]
> > 某个输出的特征维度反了。这里我有两种解决方案，第一种是在acl 那边的模型后处理做修改，第二种是直接修改onnx模型，但是我都忘记怎么操作了，要不我直接给你最后的om的模型？
> 
> 首先感谢大佬，抱歉，这个模型的下载链接失效了，可以麻烦您再补一个吗，谢谢啦

https://cowtransfer.com/s/d426d98829134f 点击链接查看 [ alphapose.om ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 mb9tz1 查看；
